[tox]
envlist = py35, py36, py37, py38, lint, pylint, cov
skip_missing_interpreters = True

[testenv]
deps =
    -r{toxinidir}/requirements_all.txt
    -r{toxinidir}/requirements_test.txt
commands =
    pytest {posargs}

[testenv:lint]
basepython = {env:PYTHON3_PATH:python3}
deps =
    -r{toxinidir}/requirements_test.txt
commands =
    flake8 {posargs}
    pydocstyle {posargs:pytexttv tests}

[testenv:pylint]
basepython = {env:PYTHON3_PATH:python3}
deps =
    -r{toxinidir}/requirements_all.txt
    -r{toxinidir}/requirements_test.txt
commands =
    pylint {posargs} pytexttv

[testenv:cov]
basepython = {env:PYTHON3_PATH:python3}
deps =
    -r{toxinidir}/requirements_all.txt
    -r{toxinidir}/requirements_test.txt
commands =
    pytest --cov --cov-report= {posargs}
