---
name: Continuous Integration

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

jobs:
  pre-commit:
    name: Run pre-commit on all files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-python@v3.0.0
        with:
          python-version: 3.x
      - uses: pre-commit/action@v2.0.3
